Always run in the right dir

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,11 +1,20 @@
 #!/usr/bin/env zsh
-if [[ -z $STOW_FOLDERS ]]; then
-    # Get list of folders in the dotfiles directory
-    STOW_FOLDERS=$(ls -d */ | sed 's/\///g' | tr '\n' ',' | sed 's/,$//')
-fi
-
 if [[ -z $DOTFILES ]]; then
     DOTFILES=$HOME/.config/dotfiles
+fi
+
+if [[ ! -d $DOTFILES ]]; then
+    echo "Dotfiles directory not found: $DOTFILES"
+    exit 1
+fi
+
+if [[ -z $STOW_FOLDERS ]]; then
+    # Get list of folders in the dotfiles directory
+    pushd "$DOTFILES" >/dev/null || exit 1
+    STOW_FOLDERS=$(printf '%s,' */)
+    STOW_FOLDERS=${STOW_FOLDERS//\//}
+    STOW_FOLDERS=${STOW_FOLDERS%,}
+    popd >/dev/null || exit 1
 fi
 
 # -----------------------------
@@ -13,27 +22,27 @@ fi
 # -----------------------------
 echo "Backup existing dotfiles"
 if [[ -f $HOME/.zshrc ]]; then
-    mkdir -p $DOTFILES/backup
-    mv $HOME/.zshrc $DOTFILES/backup
+    mkdir -p "$DOTFILES/backup"
+    mv "$HOME/.zshrc" "$DOTFILES/backup"
 fi
 
 if [[ -f $HOME/.editorconfig ]]; then
-    mkdir -p $DOTFILES/backup
-    mv $HOME/.editorconfig $DOTFILES/backup
+    mkdir -p "$DOTFILES/backup"
+    mv "$HOME/.editorconfig" "$DOTFILES/backup"
 fi
 
 if [[ -f $HOME/.config/ghostty/config.toml ]]; then
-    mkdir -p $DOTFILES/backup/.config/ghostty
-    mv $HOME/.config/ghostty/config.toml $DOTFILES/backup/.config/ghostty
+    mkdir -p "$DOTFILES/backup/.config/ghostty"
+    mv "$HOME/.config/ghostty/config.toml" "$DOTFILES/backup/.config/ghostty"
 fi
 
 if [[ -d $HOME/.config/nvim ]]; then
-    mkdir -p $DOTFILES/backup/.config
-    mv $HOME/.config/nvim $DOTFILES/backup/.config
+    mkdir -p "$DOTFILES/backup/.config"
+    mv "$HOME/.config/nvim" "$DOTFILES/backup/.config"
 fi
 
-pushd $DOTFILES
-for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
+pushd "$DOTFILES" >/dev/null || exit 1
+for folder in ${(s:,:)STOW_FOLDERS}
 do
     # Ignore backup folder
     if [[ $folder == "backup" ]]; then
@@ -41,11 +50,11 @@ do
     fi
 
     echo "stow $folder"
-    stow -D $folder
+    stow -D "$folder"
     if [[ $folder == "opencode" ]]; then
-        stow --no-folding --adopt $folder
+        stow --no-folding --adopt "$folder"
     else
-        stow --adopt $folder
+        stow --adopt "$folder"
     fi
 done
-popd
+popd >/dev/null || exit 1
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,15 +1,24 @@
 #!/usr/bin/env zsh
-if [[ -z $STOW_FOLDERS ]]; then
-    # Get list of folders in the dotfiles directory
-    STOW_FOLDERS=$(ls -d */ | sed 's/\///g' | tr '\n' ',' | sed 's/,$//')
-fi
-
 if [[ -z $DOTFILES ]]; then
     DOTFILES=$HOME/.config/dotfiles
 fi
 
-pushd $DOTFILES
-for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
+if [[ ! -d $DOTFILES ]]; then
+    echo "Dotfiles directory not found: $DOTFILES"
+    exit 1
+fi
+
+if [[ -z $STOW_FOLDERS ]]; then
+    # Get list of folders in the dotfiles directory
+    pushd "$DOTFILES" >/dev/null || exit 1
+    STOW_FOLDERS=$(printf '%s,' */)
+    STOW_FOLDERS=${STOW_FOLDERS//\//}
+    STOW_FOLDERS=${STOW_FOLDERS%,}
+    popd >/dev/null || exit 1
+fi
+
+pushd "$DOTFILES" >/dev/null || exit 1
+for folder in ${(s:,:)STOW_FOLDERS}
 do
     # Ignore backup folder
     if [[ $folder == "backup" ]]; then
@@ -17,6 +26,6 @@ do
     fi
 
     echo "stow $folder"
-    stow $folder
+    stow "$folder"
 done
-popd
+popd >/dev/null || exit 1
